version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - ".github/**/*"
    schedule:
      interval: "monthly"
    labels:
      - "actions-update"
    groups:
      actions-deps:
        patterns:
          - "*"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependency-update"
    groups:
      dev-deps:
        dependency-type: "development"
      prod-deps:
        dependency-type: "production"
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "release/1.7.x"
    schedule:
      interval: "weekly"
    labels:
      - "dependency-update"
    groups:
      dev-deps:
        dependency-type: "development"
      prod-deps:
        dependency-type: "production"
    ignore:
      - dependency-name: "org.springframework.boot:spring-boot*"
        versions:
          - "4.x"
